apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cilistapp.k8s.local
  name: nodes-ap-southeast-1a-monitoring
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220810
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.medium
  manager: CloudGroup
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-southeast-1a-monitoring
  role: Node
  taints:
  - dedicated=monitoring:NoSchedule
  nodeLabels:
    nodepool: monitoring
  subnets:
  - ap-southeast-1a
